geaje/Controllers/custBookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using geaje.DataContext;
using geaje.Models;

namespace geaje.Controllers
{
    public class custBookController : Controller
    {
        private ApplicationDBContext db = new ApplicationDBContext();

        

        // GET: custBook/Details/5
       
        

        // GET: custBook/Create
        public ActionResult Create()
        {
            ViewBag.id_venue = new SelectList(db.venues, "venue_id", "venue_name");
            return View();
        }

        // POST: custBook/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "booking_id,customer_name,id_venue,tanggal_book,lama_book,no_hp")] bookModel bookModel)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(bookModel);
                db.SaveChanges();
                return RedirectToAction("Index","customer");
            }

            ViewBag.id_venue = new SelectList(db.venues, "venue_id", "venue_name", bookModel.id_venue);
            return View(bookModel);
        }

        // GET: custBook/Edit/5
        
    }
}

geaje/Controllers/customerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using geaje.DataContext;
using geaje.Models;

namespace geaje.Controllers
{
    public class customerController : Controller
    {
        private ApplicationDBContext db = new ApplicationDBContext();

        // GET: customer
        public ActionResult Index()
        {
            var venues = db.venues.Include(v => v.desaModel).Include(v => v.kecModel).Include(v => v.kotaModel);
            return View(venues.ToList());
        }

        // GET: customer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null || db.venues == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var venue = db.venues
                .Include(v => v.desaModel)
                .Include(v => v.kecModel)
                .Include(v => v.kotaModel)
                .FirstOrDefault(m => m.venue_id == id);

            if (venue == null)
            {
                return HttpNotFound();
            }
            return View(venue);
        }

    }
}

geaje/Controllers/loginController.cs
using geaje.DataContext;
using geaje.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace geaje.Controllers
{
    public class loginController : Controller
    {
        // GET: login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Autherize(adminModel adminM)
        {
            using (ApplicationDBContext db = new ApplicationDBContext())
            {
                var admin = db.admins.Where(a => a.username.Equals(adminM.username) && a.password.Equals(adminM.password)).FirstOrDefault();
                if (admin != null)
                {
                    Session["admin_id"] = admin.admin_id;
                    return RedirectToAction("Index", "adminBook");


                }
                else
                {

                    return View("Index");
                }
                return View();
            }

        }
    }
}

geaje/Views/customer/Details.cshtml
@model geaje.Models.venueModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detail Venue</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        h1 {
            font-family: Break Dance;
            color: #DA1C5C;
            position: absolute;
            left: 40%;
        }

        .batas {
            margin-top: 100px;
        }
        body {
            margin-left: 50px;
            margin-right: 50px;
        }
        h2 {
            font-family: poppins;
            margin-bottom: 20px;
            color: #2BAEC0;
        }
        .detail {
            position: absolute;
            left: 40%;
            top: 30%;
            border: 1px solid #DA1C5C;
            padding-left: 30px;
            padding-right: 30px;
            background-color: #DA1C5C;
            border-radius: 8px;
            margin-bottom: 50px;
        }
        dd {
            margin-bottom: 10px;
            color: white;
        }
        dt {
            color: #2BAEC0;
        }
    </style>
</head>
<body>
    <h1>Welcome to Geaje</h1>
    <div class="batas"></div>
    <div class="detail">
        <h2>Detail Venue</h2>
        <hr />
        <dl class="">
            <dt>
                @Html.DisplayNameFor(model => model.venue_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.venue_name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.desaModel.desa_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.desaModel.desa_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.kecModel.kec_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.kecModel.kec_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.kotaModel.kota_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.kotaModel.kota_name)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.alamat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.alamat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.deskripsi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.deskripsi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.harga)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.harga)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Back", "Index", new { }, new { @class = "btn", @style= "background-color: #1f1e1e;color: #ffff" })
    </p>
    <hr />
</body>
</html>

geaje/Views/customer/Index.cshtml
@model IEnumerable<geaje.Models.venueModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        h1 {
            font-family: Break Dance;
            color: #DA1C5C;
            position:absolute;
            left:40%;
        }
        .batas{
            margin-top:100px;
        }
        h3{
            font-family:Poppins;
            margin-bottom:20px;
             
        }
        .admin{
            position:absolute;
            left:91%;
        }
        
        
    </style>
</head>
<body style="margin-left:50px;margin-right:50px;">
    <h1>Welcome to Geaje</h1>
    <div class="batas"></div>
    <div class="admin"><td>@Html.ActionLink("Admin", "Index", "login", new { }, new { @class = "btn", @style = "background-color:#46e353;color:#ffff;" })</td></div>
    <tr>
        <td>@Html.ActionLink("Buat Booking", "Create", "custBook", new { }, new {@class="btn",@style= "background-color:#DA1C5C;color:#ffff;" })</td>
        <td></td>
        
    </tr>
        
        
    </p>
    <center>
        <h3>Daftar Gedung</h3>
    </center>
    
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.venue_name)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.harga)
            </th>
            <th>
                Detail
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.venue_name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.harga)
                </td>
                <td>

                    @Html.ActionLink("Details", "Details", new { id = item.venue_id }, new { @class = "btn", @style = "background-color:#ffee6e;color:black;" })
                    
                </td>
            </tr>
        }

    </table>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
    }
</body>
</html>